/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppWorkspaceRouteRouteImport } from './routes/_app/_workspace/route'
import { Route as AppWorkspaceIndexRouteImport } from './routes/_app/_workspace/index'
import { Route as AppWorkspaceModelsRouteImport } from './routes/_app/_workspace/models'
import { Route as AppWorkspaceMembersRouteImport } from './routes/_app/_workspace/members'
import { Route as AppWorkspaceChatbotsRouteImport } from './routes/_app/_workspace/chatbots'
import { Route as AppWorkspaceKnowledgeBasesRouteRouteImport } from './routes/_app/_workspace/knowledge-bases/route'
import { Route as AppWorkspaceKnowledgeBasesIndexRouteImport } from './routes/_app/_workspace/knowledge-bases/index'
import { Route as AppWorkspaceKnowledgeBasesKnowledgeBaseIdRouteImport } from './routes/_app/_workspace/knowledge-bases/$knowledgeBaseId'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkspaceRouteRoute = AppWorkspaceRouteRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkspaceIndexRoute = AppWorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWorkspaceRouteRoute,
} as any)
const AppWorkspaceModelsRoute = AppWorkspaceModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AppWorkspaceRouteRoute,
} as any)
const AppWorkspaceMembersRoute = AppWorkspaceMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppWorkspaceRouteRoute,
} as any)
const AppWorkspaceChatbotsRoute = AppWorkspaceChatbotsRouteImport.update({
  id: '/chatbots',
  path: '/chatbots',
  getParentRoute: () => AppWorkspaceRouteRoute,
} as any)
const AppWorkspaceKnowledgeBasesRouteRoute =
  AppWorkspaceKnowledgeBasesRouteRouteImport.update({
    id: '/knowledge-bases',
    path: '/knowledge-bases',
    getParentRoute: () => AppWorkspaceRouteRoute,
  } as any)
const AppWorkspaceKnowledgeBasesIndexRoute =
  AppWorkspaceKnowledgeBasesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWorkspaceKnowledgeBasesRouteRoute,
  } as any)
const AppWorkspaceKnowledgeBasesKnowledgeBaseIdRoute =
  AppWorkspaceKnowledgeBasesKnowledgeBaseIdRouteImport.update({
    id: '/$knowledgeBaseId',
    path: '/$knowledgeBaseId',
    getParentRoute: () => AppWorkspaceKnowledgeBasesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppWorkspaceIndexRoute
  '/onboarding': typeof AppOnboardingRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/knowledge-bases': typeof AppWorkspaceKnowledgeBasesRouteRouteWithChildren
  '/chatbots': typeof AppWorkspaceChatbotsRoute
  '/members': typeof AppWorkspaceMembersRoute
  '/models': typeof AppWorkspaceModelsRoute
  '/knowledge-bases/$knowledgeBaseId': typeof AppWorkspaceKnowledgeBasesKnowledgeBaseIdRoute
  '/knowledge-bases/': typeof AppWorkspaceKnowledgeBasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppWorkspaceIndexRoute
  '/onboarding': typeof AppOnboardingRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/chatbots': typeof AppWorkspaceChatbotsRoute
  '/members': typeof AppWorkspaceMembersRoute
  '/models': typeof AppWorkspaceModelsRoute
  '/knowledge-bases/$knowledgeBaseId': typeof AppWorkspaceKnowledgeBasesKnowledgeBaseIdRoute
  '/knowledge-bases': typeof AppWorkspaceKnowledgeBasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_app/_workspace': typeof AppWorkspaceRouteRouteWithChildren
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_app/_workspace/knowledge-bases': typeof AppWorkspaceKnowledgeBasesRouteRouteWithChildren
  '/_app/_workspace/chatbots': typeof AppWorkspaceChatbotsRoute
  '/_app/_workspace/members': typeof AppWorkspaceMembersRoute
  '/_app/_workspace/models': typeof AppWorkspaceModelsRoute
  '/_app/_workspace/': typeof AppWorkspaceIndexRoute
  '/_app/_workspace/knowledge-bases/$knowledgeBaseId': typeof AppWorkspaceKnowledgeBasesKnowledgeBaseIdRoute
  '/_app/_workspace/knowledge-bases/': typeof AppWorkspaceKnowledgeBasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/knowledge-bases'
    | '/chatbots'
    | '/members'
    | '/models'
    | '/knowledge-bases/$knowledgeBaseId'
    | '/knowledge-bases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/chatbots'
    | '/members'
    | '/models'
    | '/knowledge-bases/$knowledgeBaseId'
    | '/knowledge-bases'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/_workspace'
    | '/_app/onboarding'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_app/_workspace/knowledge-bases'
    | '/_app/_workspace/chatbots'
    | '/_app/_workspace/members'
    | '/_app/_workspace/models'
    | '/_app/_workspace/'
    | '/_app/_workspace/knowledge-bases/$knowledgeBaseId'
    | '/_app/_workspace/knowledge-bases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_workspace': {
      id: '/_app/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppWorkspaceRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_workspace/': {
      id: '/_app/_workspace/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppWorkspaceIndexRouteImport
      parentRoute: typeof AppWorkspaceRouteRoute
    }
    '/_app/_workspace/models': {
      id: '/_app/_workspace/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AppWorkspaceModelsRouteImport
      parentRoute: typeof AppWorkspaceRouteRoute
    }
    '/_app/_workspace/members': {
      id: '/_app/_workspace/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AppWorkspaceMembersRouteImport
      parentRoute: typeof AppWorkspaceRouteRoute
    }
    '/_app/_workspace/chatbots': {
      id: '/_app/_workspace/chatbots'
      path: '/chatbots'
      fullPath: '/chatbots'
      preLoaderRoute: typeof AppWorkspaceChatbotsRouteImport
      parentRoute: typeof AppWorkspaceRouteRoute
    }
    '/_app/_workspace/knowledge-bases': {
      id: '/_app/_workspace/knowledge-bases'
      path: '/knowledge-bases'
      fullPath: '/knowledge-bases'
      preLoaderRoute: typeof AppWorkspaceKnowledgeBasesRouteRouteImport
      parentRoute: typeof AppWorkspaceRouteRoute
    }
    '/_app/_workspace/knowledge-bases/': {
      id: '/_app/_workspace/knowledge-bases/'
      path: '/'
      fullPath: '/knowledge-bases/'
      preLoaderRoute: typeof AppWorkspaceKnowledgeBasesIndexRouteImport
      parentRoute: typeof AppWorkspaceKnowledgeBasesRouteRoute
    }
    '/_app/_workspace/knowledge-bases/$knowledgeBaseId': {
      id: '/_app/_workspace/knowledge-bases/$knowledgeBaseId'
      path: '/$knowledgeBaseId'
      fullPath: '/knowledge-bases/$knowledgeBaseId'
      preLoaderRoute: typeof AppWorkspaceKnowledgeBasesKnowledgeBaseIdRouteImport
      parentRoute: typeof AppWorkspaceKnowledgeBasesRouteRoute
    }
  }
}

interface AppWorkspaceKnowledgeBasesRouteRouteChildren {
  AppWorkspaceKnowledgeBasesKnowledgeBaseIdRoute: typeof AppWorkspaceKnowledgeBasesKnowledgeBaseIdRoute
  AppWorkspaceKnowledgeBasesIndexRoute: typeof AppWorkspaceKnowledgeBasesIndexRoute
}

const AppWorkspaceKnowledgeBasesRouteRouteChildren: AppWorkspaceKnowledgeBasesRouteRouteChildren =
  {
    AppWorkspaceKnowledgeBasesKnowledgeBaseIdRoute:
      AppWorkspaceKnowledgeBasesKnowledgeBaseIdRoute,
    AppWorkspaceKnowledgeBasesIndexRoute: AppWorkspaceKnowledgeBasesIndexRoute,
  }

const AppWorkspaceKnowledgeBasesRouteRouteWithChildren =
  AppWorkspaceKnowledgeBasesRouteRoute._addFileChildren(
    AppWorkspaceKnowledgeBasesRouteRouteChildren,
  )

interface AppWorkspaceRouteRouteChildren {
  AppWorkspaceKnowledgeBasesRouteRoute: typeof AppWorkspaceKnowledgeBasesRouteRouteWithChildren
  AppWorkspaceChatbotsRoute: typeof AppWorkspaceChatbotsRoute
  AppWorkspaceMembersRoute: typeof AppWorkspaceMembersRoute
  AppWorkspaceModelsRoute: typeof AppWorkspaceModelsRoute
  AppWorkspaceIndexRoute: typeof AppWorkspaceIndexRoute
}

const AppWorkspaceRouteRouteChildren: AppWorkspaceRouteRouteChildren = {
  AppWorkspaceKnowledgeBasesRouteRoute:
    AppWorkspaceKnowledgeBasesRouteRouteWithChildren,
  AppWorkspaceChatbotsRoute: AppWorkspaceChatbotsRoute,
  AppWorkspaceMembersRoute: AppWorkspaceMembersRoute,
  AppWorkspaceModelsRoute: AppWorkspaceModelsRoute,
  AppWorkspaceIndexRoute: AppWorkspaceIndexRoute,
}

const AppWorkspaceRouteRouteWithChildren =
  AppWorkspaceRouteRoute._addFileChildren(AppWorkspaceRouteRouteChildren)

interface AppRouteRouteChildren {
  AppWorkspaceRouteRoute: typeof AppWorkspaceRouteRouteWithChildren
  AppOnboardingRoute: typeof AppOnboardingRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppWorkspaceRouteRoute: AppWorkspaceRouteRouteWithChildren,
  AppOnboardingRoute: AppOnboardingRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
